### ISSUE TITLE
⭐️ Feature: Project Commit Flow

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#3141]
## Problem Statement
As part of the new `Project` level in the hierarchy - we need to allow the user to perform a single commit on pending changes from multiple resources. 
The single commit will trigger multiple build processes, one for each resource. 

For example, the user has a project with two services - Customer service and Order service. 
The user created a new field in the Customer service and also created a new entity in the Order service. 
The user should be able to commit the two changes at once, trigger the build in each service, and get the updated code for each service. 

## Proposed Work
- Move the Commit model to the project level
- Each commit can be linked to multiple builds. Each build is linked to a different service. 

## Spec
- [Figma Design](https://www.figma.com/file/71Ut91hFxC7cpLbJQQMsgP/%23none---Commit-Update-v3?node-id=1416%3A8629) (owned by @alexbass86)

## Subtasks
- [x]  #3283 
- [x]  #3296 
- [x] #3400
- [x] #3410
- [x] #3417
- [ ] Project Layout - footer - Show commits info
- [x] #3447
- [x] compare diff page - new layout and design
- [x] #3499 
- [x] #3448
- [x] Project Layout - new project navigation menu

**Comment by souravjain540** [comment]
@yuval-hazaz this feature is for the engineering team. Right?

**Comment by yuval-hazaz** [comment]
yes

**Comment by arielweinberger** [comment]
Released in 0.15.0
