### ISSUE TITLE
☂️ Testing Automation

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4475]
- [x] https://github.com/amplication/amplication/issues/4488
- [ ] Integrate E2E PoC into amplication monorepo and run e2e on `master` changes
- [ ] SPIKE - Define a set of e2e testing flows from the client application.

**Comment by overbit** [comment]
Great PoC, the only comment is about adding a simple README to allow new started to try to run these smoke tests.

We will need to decide now, where to host this solution (new repo or monorepo) as we as how we going to run the e2e. 
Things to consider:
1. Nx framework e2e https://nx.dev/packages/nx-plugin/generators/e2e-project#@nrwl/nx-plugin:e2e-project
