### ISSUE TITLE
⭐  New Onboarding Flow

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5013]
- [x] #5015
- [x] #5016
- [x] #5017
- [x] #5018

**Design** - https://www.figma.com/file/fGHkvGfTxVm9P0RsVXYk9b/%23none---New-user-Onboarding-Flow-v2?node-id=2041%3A14924&t=fwIHz1uun76xuEyi-1

**Comment by GreenMachine01** [comment]
1. UI
2. Logic
3. New User vs Existing User (Code Build + Git open)
4. Different texts for new user vs existing
5. Handle special cases
6. BI Events
7. Animations

**Comment by overbit** [comment]
Notes from meeting

- [ ] Bare flow for new user with hardcoded data
- [ ] Update DB plugins with a new category for on-boarding
- [ ] DB page with dynamic population
- [ ] Footer component
- [ ] Existing user flow
- [ ] Git connect (create project, create blank resource / create blank service)
- [ ] Extend plugin API to get plugin by category
- [ ] _Update PR message with link back to amplication service/project/workspace_

**Comment by GreenMachine01** [comment]
@morhag90 @overbit 
The option to navigate with "Back" between the steps is a nice to have feature and can be added later (phase II)

**Comment by overbit** [comment]
@GreenMachine01  can we add the figma link to the description of this Epic?
