### ISSUE TITLE
As a user - I don't want to be able to select only supported plugins that are not deprecated

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#5163]
## Description

Currently, as a user, I can select any version of a plugin and it can cause issues in the generated code or in the code generation process where an old plugin is not supported by amplication DSG anymore.
In the case of existing applications that are configured with a plugin version that gets deprecated, the DSG build log should show a message about the deprecated plugin and a sentence with instructions on how to update it.

This requirement comes from the work done on #4431, which highlighted that some old plugins (pre-webpack) might not work with the DSG dynamic installation.

## Tech Notes

- [ ] Deprecate old plugins versions
- [x] Update plugin API to only collect NOT-deprecated packages versions #5207  
- [x] Update DSG to print a warning log in the build log wherever it tries to install a deprecated plugin #5171

## Acceptance criteria

user with a deprecated plugin configured already
* *Given* a user with an existing plugin configured to version `x.y.z`
* *When* it runs a new code generation build
* *Then* a new message will be printed warning the user that is using a deprecated plugin

user selects a specific version
* *Given* a user 
* *When* it goes to select a specific plugin version
* *Then* only no-deprecated plugin versions are displayed in the dropdown

**Comment by abrl91** [comment]
passed - ✅


https://user-images.githubusercontent.com/39680385/219605506-6ad7884b-1a3a-40ab-876e-0d1476169e1e.mov
