### ISSUE TITLE
🔍 Epic: [Smart git] stage 2

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5272]
## Details

Stage two for the smart git strategy is a list of several "bonus" tasks that is a improvement of work for our users.

## Tasks

- [ ] Wrap the logic of the process as a transation
- [ ] Having the diff.patch file even if the user deleted the amplication branch
- [ ] Switch to a logger instead of console logger
- [x] #5321
