### ISSUE TITLE
As User - I want to be able to login into Amplication via SSO

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5423]
As a user, I want to be able to login into Amplication via SSO so that I can easily access my account without having to remember multiple passwords.

**Acceptance Criteria:**

1. Amplication supports seamless login via SSO.
2. When the user navigates to the Amplication app, they should be automatically logged in via their existing SSO session.
3. The user should be able to access all of their resources and perform all necessary actions within the app without having to enter any additional login credentials.
4. New accounts should be created using the user's company email address.
5. The user should be able to log out of their Amplication account at any time, and the SSO session should be terminated simultaneously.
6. The user should be notified if there are any errors during the login process, such as invalid credentials or network connectivity issues. The error message should be clear and actionable.
7. The solution we go with should be generic and support the future addition of other SSO providers
8. The login page should not mention SSO apart from the extra link to `Continue with SSO`

![image](https://github.com/amplication/amplication/assets/2861984/a323a79c-b4aa-4ca8-bcb3-e2b301c4380c)

# Tasks

- [x] Configure staging and production tenants in US. ( Terraform or DeployCLI ) 
    - https://github.com/amplication/auth0/pull/1
    - https://github.com/amplication/auth0/pull/2
- [x] Configure universal login customisation for each amplication accounts. ( Fix style in agreement with design system )
   - https://github.com/amplication/amplication/pull/5894/commits/f4e1d6c8e36bfec9c339edafac940c375582f90e
- [x] Configure `amplication-client` and `amplication-server` with tenants configurations
   - https://github.com/amplication/amplication-manifests/pull/136
- [x] Create Test group for amplication SSO
- [x] Configure amplication SSO  
   - Configured in `sandbox` and `staging` to allow QA 
- [x] Document on Notion the e2e setup
   - https://www.notion.so/amplication/Amplication-SSO-Auth-c8479b2dc35947f6a2cf3abfd8280a25 

### Testing tips
During the trial period for our dev tenant, we have access to enterprise connections so an AmplicationEngineering SSO integration has been configured to allow manual testing of the full end to end login flow as a SSO user

**Comment by mulygottlieb** [comment]
Passed QA


![Image](https://github.com/amplication/amplication/assets/1912933/e1ece1fb-963d-4f2b-97f8-8ccd5a9d119c)


Logging in with my @amplication.com user works with SSO:


![Image](https://github.com/amplication/amplication/assets/1912933/f19b6904-0edd-45fa-9925-c186f5c5bd8a)





![Image](https://github.com/amplication/amplication/assets/1912933/c1a35f9c-6ae5-4f03-b0ad-710a06824517)
