### ISSUE TITLE
Adding support for Bitbucket

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#5812]
- [ ] create the new components for supporting multiple providers

Figma - https://www.figma.com/file/EXpu3W16xQDQ6NnEpzQE9R/%23none---Supporting-more-Git-providers?node-id=2041%3A14924&t=snyREHPvdQKyqgFU-1

- choosing the provider
![image](https://user-images.githubusercontent.com/39680385/232458264-ca8b28a3-896c-4913-b693-721910f69d1e.png)

and lock for enterprise only
![image](https://user-images.githubusercontent.com/39680385/232458694-5910973c-45ac-4f99-8de1-2957e4ded683.png)

inside a dialog when adding a new provider
![image](https://user-images.githubusercontent.com/39680385/232458827-d696599f-3ba7-40ea-96c8-e3c4803769ad.png)

- The workspace selector:
![image](https://user-images.githubusercontent.com/39680385/232458428-584c41a9-47f6-4ad7-8679-bb70a888cbfb.png)

![image](https://user-images.githubusercontent.com/39680385/232458532-86185e74-2ce0-4a1c-b3f6-1df06ff9bb00.png)

- [ ] update the service wizard and the sync with the git page to allow multiple git provider selection
- [ ] handle Bitbucket restrictions such as choosing a workspace and being enabled only for enterprise users

**Comment by mulygottlieb** [comment]
@abrl91 I see this is in CR status on the board but there is no linked PR to review here.

**Comment by abrl91** [comment]
Fixed by https://github.com/amplication/amplication/pull/5890
