### ISSUE TITLE
🔌  Plugin Bug Report [deployment-helm-chart]: different bugs included in the 0.0.2 version of the plugin

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#5843]
### What happened?

List of issues encountered when doing a bug hunt for the `deploymen-helm-chart` plugin:
- [x] setting `root_level` still not defaulting to the root of the repository when using a mono-repository
```
expected location when root_level 'true': ./<directory_name>/<service_name>
```
- [x] setting `directory_name` not working as expected, eg.,:
```
setting configuration directory_name 'helm-charts' > apps/<service-name>/helm-<service-name>s/chart/Chart.yaml
```
- [ ] one of the configmap values - i.e., compose_project_name - still uses the variable instead of the value:
```
COMPOSE_PROJECT_NAME: amp_${resourceId}
```

### What you expected to happen

That the use of the different configurations leads to their respective expected out come, e.g., root_level > actual root level of the repository, directory_name > no problems with the service name being inserted half way through the variable and adding another directory.

### How to reproduce

Run different configurations for the deployment-helm-chart plugin according to the problems above.

### Amplication version

deploymen-helm-chart@0.0.2

### Are you willing to submit PR?

Yes I am willing to submit a PR!
