### ISSUE TITLE
As a plugin developer - I want to enforce that my plugin requires a mandatory "user" entity

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#5853]
**This task has a prerequisite of completing https://github.com/amplication/amplication/issues/5851 first**

As a plugin developer, I want a "system settings" option for my plugin that signals Amplication that my plugin requires some entity that serves as the "identity entity" (AKA "authentication entity).
If this setting appears on a plugin then:

1. You cannot install this plugin if you don't have such an entity defined in your service
2. If the plugin is defined, you are not allowed to delete that entity

For this phase, as we do not yet allow to choose the authentication entity - this will be mapped to the "User" entity. In the future, when we allow choosing which entity is the authentication entity - it will become a more generic solution.

- [x] Verify that https://github.com/amplication/amplication/issues/5851 is complete
- [x] Add a new flag that the server is aware of, to the _system settings_ part of the plugin configuration that is called _requires auth entity_ and has a Boolean value
- [x] During plugin installation, verify that the User entity exists on the service, otherwise display a message that you cannot install this plugin until you have a user entity (check with Erez for texts)
- [ ] If such a plugin is already installed, when we implement https://github.com/amplication/amplication/issues/5405 we should block the operation with an error message
- [ ] Add this property to the latest version of the _NestJS Auth Module_ plugin

**Design:**
If not provided use our design system to show the notification

**Notification Text:**
"Plugin installation cannot proceed as an entity for authentication has not been defined. Please refer to our documentation on how to define an entity for authentication before attempting to install the authentication plugin. [link to documentation]"

**Comment by mulygottlieb** [comment]
QA Passed:


![Image](https://github.com/amplication/amplication/assets/1912933/97fa67d4-699a-4f77-9301-1c4b00435325)





![Image](https://github.com/amplication/amplication/assets/1912933/6dd1492b-a109-46f1-b5ec-63282d865471)
