### ISSUE TITLE
DB schema import - leftovers

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6541]
The following three were fixed by: https://github.com/amplication/amplication/pull/6543 and #6552
- [x] logs for big schemas 
- [x] logs are not coming in batches
- [x] for big schemas - kafka keeps processing messages

--- 

- [x] kafka message size - fixed by AWS configuration
- [x] fix validate upload handling - https://github.com/amplication/amplication/pull/6547
