### ISSUE TITLE
DB Schema Import - update the Notion page and the docs

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#6682]
- [ ] new data types: Decimal and BigInt
- [x] handling id field
- [x] removing `@default(some-value) from id fields
- [x] mentioning the issue with the order of generated prisma and having PK field that is not named id and not PK that named id: https://github.com/amplication/amplication/issues/6681
