### ISSUE TITLE
🔍 Epic: DSG Versioning

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#6720]
https://www.notion.so/amplication/DSG-Versions-75c6f5c7406849cfb816afb1cb0238a9
Updated diagram https://excalidraw.com/#room=343e7e622371281ad2e6,Q5plna3TgIYrJTRtVPSwmw

## `data-service-generator`
- [x] amplication/amplication#6730

## Continuous integration
- [x] amplication/amplication#6786
- [x] amplication/amplication#6785
- [x] amplication/amplication#6810
- [x] amplication/amplication#6812
- [x] update ECR lifecycle to avoid deleting versions / create ECR lifecycle to never delete prod tagged versions

## `dsg-catalog`
- [x] amplication/amplication#6775
    Add new entity `Version` with 
      - name (tag name)
      - description
      - createdAt
      - updateAt
      - deprecated (bool)
      - deletedAt
- [ ] amplication/amplication#6723
- [x] amplication/amplication#6855
   Gotchas: 
   - `description` will manually populated by engineer/product (maybe leveraging package.json description)
   - when a version has `deletedAt` populated, the mutation will delete the container from ECR
   - when a version present in the db is not available anymore in ECR, that version needs to be updated with `deletedAt`
 - [x] #6884
 - [x] #6885

## Infrastructure
- [x] amplication/amplication#6724
- [x] amplication/amplication#6731
- [x] amplication/amplication-infrastructure-next#223
- [ ] #6889
- [x] amplication/amplication#6817
- [x] amplication/amplication-cluster-configuration#21

## `build-manager`
- [x] amplication/amplication#6736
  - update code-generation-request event to include `code-generator-version` and user preference on specific vs latest vs latest minor version
  - add logic to use either `code-generator-version` of a service or the latest during the createBuild

## `server`
- [x] amplication/amplication#6818
- [x] amplication/amplication#6800
- [x] amplication/amplication#6848
- [x] #6879

## `client`
- [x] amplication/amplication#6721
   add `code-generator-version` to service settings. 
  The list of versions and status (obsolete) will be retrieved by quering `dsg-catalog`
  User will be able to select the `latest` version or a specific version or the latest of a minor version

## Other
- [x] https://github.com/amplication/amplication/issues/6871
- [x] https://github.com/amplication/amplication/issues/6908

# Open points

## obsolete versions
- [ ] Users should be notified that the selected `code-generator-version` gets obsoleted.
  Should we use:
  - code generation build log (difficult, `dsg` will need to make http request to `dsg-catalog`)
  - notification service
  - resource/service page
  
## Plugin and DSG versions
- [ ] how to handle dsg-version specific plugin?
   potential ideas:
    - Plugin driven logic (context will have dsg version so plugin will produce different code based on version)
    - DSG driven logic
    - plugin should declare what `code-generator-version` is supported

**Comment by abrl91** [comment]
Tests:

![image](https://github.com/amplication/amplication/assets/39680385/7d6667b2-c891-4226-9ef5-6842215f8daf)

![image](https://github.com/amplication/amplication/assets/39680385/d39d4dd5-f126-40ac-9691-8f088bcd2162)

next build because I chose automatic update
![image](https://github.com/amplication/amplication/assets/39680385/a140671d-e141-47e2-9832-a4c8179f3fd6)

then I chose
![image](https://github.com/amplication/amplication/assets/39680385/849d7c62-3556-411f-b7d7-ada536353885)

and the build:
![image](https://github.com/amplication/amplication/assets/39680385/7381ee3c-011e-4e36-80a9-b0591fbf44ea)
