### ISSUE TITLE
As PO - I want to improve the notifications feature

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#6898]
- [x]  Smaller icon in the top bar (icon size 16px in a 20px frame)

![Image](https://github.com/amplication/amplication/assets/112330500/70b1c8a2-5958-460d-8381-45f3f7ef55ba)

- [x]  Remove the Novu logo from the notifications panel

- [x] Build ID should show only the last 8 numbers of the build ID

![Image](https://github.com/amplication/amplication/assets/112330500/b59b4f44-aa71-42ab-ba40-23b79cf2ab98)

- [x]  I added an action button to the notification - we need to set an action when its pressed

- [x]  The email arrives with an empty link.

- [ ]  Show how to use metadata in the email (Project Name, Build ID, Date & Time of Build)

- [x]  Force the font family we want to use on the texts (Roboto)

**Comment by GreenMachine01** [comment]
@barshimi the action needs to open the build log page of the specific build.

**Comment by mulygottlieb** [comment]
@barshimi have you implemented the additional fields for the email: project name, date & time of build? I think this part is still missing in order to complete the issue

**Comment by abrl91** [comment]
- The icon is smaller
- No Novu logo
- Action button

![image](https://github.com/amplication/amplication/assets/39680385/4cd5e49a-4e83-4909-be64-3324ffb3be08)

We need to create an issue about the action button for services that were deleted because it redirects to

![image](https://github.com/amplication/amplication/assets/39680385/07c0af15-bc58-44a2-8ef8-41884dfa5f79)
