### ISSUE TITLE
Improve overall code generation time by spliting the admin-ui and the server creation into 2 dsg jobs

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7388]
## Tech notes

In order to segregate the responsibility of this split, the build manager would be the only service in charge of this task.

Potential soluion:
- when the user chooses to generate the admin, the build manager will spin up two DSG jobs
   - /${buildId}-server
   - /${buildId}-admin-ui
- when the user chooses to generate the server only, the build manager will spin up one DSG job
    - /${buildId}-server

## Related requirements

- [ ] amplication/amplication#7393
- [x] amplication/amplication-cluster-configuration#129
- [x] amplication/amplication-cluster-configuration#128
- [ ] amplication/amplication-cluster-configuration#134

**Comment by overbit** [comment]
@mulygottlieb @yuval-hazaz do we want to split the jobs for all the builds?

**Comment by mulygottlieb** [comment]
@overbit I missed your comment above. For posterity - yes, we want to split all builds for now, and in the future, we can raise a new issue (if needed) to add any kind of new logic into this decision (e.g. number of entities or other).
