### ISSUE TITLE
[Epic - BTM] As a user - I want to be able break a monolithic service into microservices

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#7581]
We want to tackle the epic of "Break the Monolith" as described in [Notion](https://www.notion.so/amplication/Break-The-Monolith-fa997c8a49224ec1a1297f7585f86c64?pvs=4).

--------------------------------------------------------------------------------------------------------------
Spec:
https://www.notion.so/amplication/Breaking-the-Monolith-Phase-1-ee82ceea689f4b15b3a422077a91d014?pvs=4

Design:
https://www.figma.com/file/SSOYJbY3vYMjwcNUABSjwd/UX%2FUI---Breaking-the-monolith-(phase-1)?type=design&node-id=757%3A1353&mode=design&t=OiiciJ4JI4asHFmn-1

--------------------------------------------------------------------------------------------------------------

This will be a large epic that we will handle in phases, and add subtasks to this epic as we go.
Ongoing list of subtasks:
- [x] #7582
- [x] #7693 
- [x] https://github.com/amplication/private-issues/issues/108
- [x] #7722 
- [x] https://github.com/amplication/private-issues/issues/110
- [x] https://github.com/amplication/amplication/issues/7817
- [x] https://github.com/amplication/amplication/issues/7818
- [x] https://github.com/amplication/amplication/issues/7819
- [x] https://github.com/amplication/amplication/issues/7821
- [ ] #8046
- [ ] https://github.com/amplication/private-issues/issues/124
- [x] #7820 
- [ ] https://github.com/amplication/private-issues/issues/128
- [ ] #8070
- [ ] #8071
- [ ] #8072
- [ ] #8073
- [ ] #8074
- [ ] #8079
- [ ] #8080
- [ ] #8081
- [ ] #8086
- [ ] #8088
- [ ] #8087
- [ ] #8134
-------- Nice to have for the AI + Preview release ----->
- [ ] #8135
- [ ] #8103

**Comment by mulygottlieb** [comment]
All sub-issues are now tracked by stand alone issues, closing this one
