### ISSUE TITLE
[Epic] Custom Actions and Types- Phase 2

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7713]
Spec-
https://www.notion.so/amplication/Custom-Types-Actions-Phase-2-b83fb9234c78419584bbb47a0fc31634?pvs=4
Design- 
TBD

**P0 issues (MUST HAVE before beta release)**
- [x]  DSG support for Custom Enum generation
- [x]  Add entitlement validation on the server as needed
- [x] Define and implement migration strategy to create default DTOs
- [x]  InputType(), ArgsType() and other graphQL decorators
- [x]  Disallow DTO deletion *and disabling* (client)
- [x]  refactor customDtoNameToPath to support multiple custom DTOs with the same name in different modules (import)

**P0.5 (before beta release)**
- [x] Add id property to DTO property or validate on change rename
- [x]  When deleting an entity (or custom module)- check if all children (actions, dtos (? might not want to delete DTOs that might be in used), props…) are also deleted and are not left orphans
- [x] Analytics (detailed in the spec)
- [x] Beta indications (where?)

The remainder of the issues are in: https://github.com/amplication/amplication/issues/8280
