### ISSUE TITLE
Epic: Custom Actions - Enums

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#8121]
### Feature description

- [ ] Create default Enums (DTOs) for OptionSet and MultiSelectOptionSet fields
- [ ] Server Side - Create custom Enums
- [ ] Client Side - Create custom Enums
- [ ] Server Side - Create custom Enum members
- [ ] Client Side - Create custom Enum members
