### ISSUE TITLE
[Epic] Custom Actions and Types - Phase 3

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8280]
Spec-
https://www.notion.so/amplication/Custom-Types-Actions-Phase-2-b83fb9234c78419584bbb47a0fc31634?pvs=4
Design- 
TBD

First part of this was handled in: https://github.com/amplication/amplication/issues/7713

**P1 issues**
- [ ]  Union type (without DTOs) ? null type ? DTO vs primitives; Remove the union type?
- [ ]  Use a flag to determine where to generate the custom DTOs (dto folder/ base folder, entity folder…) **(to discuss)**
    - We currently generate custom actions in the base file. should we keep it?
- [ ]  Creating services trigger hundreds of records (**to discuss**)
- [ ]  Use server-side logic to guess DTO props types like with entity field (**quick win?**)
- [x]  Create action/dto/enum modal (with Mor’s new modal) (**UX**)
- [ ] Create module modal L&F (**UX**)
- [ ]  Free and Trial plan experience should be adjusted to meet the behavior of other Enterprise features (tooltips etc.)
    - The following actions should be enabled for Enterprise plan only (and Trial) - "Add Module", "Add Action", "Add DTO", "Add Enum", enable / disable action (two places- in the module screen, and in the action screen itself), edit action (besides add / edit its description), edit DTO / Enum (besides add / edit its description) 
- [x]  Bug: DTO can have a member of type Enum, and a member of type DTO of type Enum. Confusing... The Enum type should be removed.
- [ ]  Bug: "The users will be able to delete empty modules that they created." - for now a custom module can be deleted even in case there are actions / DTOs in it.
- [x]  Bug: When searching for a specific module (in the "all modules" screen), choosing / pressing one module, and back to the "all modules" screen- the search string is "stuck" although not visible.

**UI/UX issues (P1/P2)**

- [X]  We need to think how we can make it clearer what is expected from a user who wants to define a new API? (**P1**)
- [ ]  The modules / Actions / DTOs should be sorted alphabetically **(P1)**
- [ ]  From the spec: "Amplication’s Actions, and DTOs will be displayed with a special indication, and they cannot be deleted/moved between modules." **(P1)**
    - Be able to filter out default actions/DTOs for better navigation
- [ ]  Bug: Choosing a module in the "all modules" search should highlight it in the menu **(P1)**.
- [ ]  Bug: After choosing to add a new DTO (enum or DTO), or Action- nothing is highlighted in the menu **(P1)**
- [ ]  When choosing to create a new type using the drop-down search modal, the modal should be closed. In addition- we should improve the performance of the new type's display, after creating new type.
- [ ]  From the spec: "New or updated DTOs / Actions, and their modules, will be marked clearly in the UI (- in the DTOs / Actions list, and in the ‘Pending Changes’ list), so it will be easy to see which DTOs / Adctions and modules were edited. Committing the changes and building will clear these indications". **(P2)**
- [ ]  From the spec: "The users will be able to move the Actions, that they created, between modules." **(P2)**
- [ ]  Searching the modules, and choosing one module should display the module screen and not the edit-module screen **(P2)**
- [ ]  Create a component to select DTOs as props (Posthog-like) (**P2**)
- [ ]  Improve the "All modules" UI **(P2)**
- [ ]  Improve the "Actions" UI **(P2)**
- [ ]  Improve the "DTOs" UI **(P2)**

**P2 issues (after beta release)**

- [ ]  Upon creation / editing - add validations (and client-side pre-enforcement) for property def (Array of null, multiple time same type, etc)
- [ ]  DSG plugin events (create custom DTO, create custom service, controller, resolver…)
- [ ]  custom action permissions (**to discuss**)
- [ ]  DTO deletion: Decide how we do validation for relations between DTOs/ Actions/ Properties, etc- DSG only / background build process / display (best-effort) relations
- [ ]  Support union types - graphQL & REST *(open issue)*
    - How does REST support union types?
- [ ]  From the spec: "The Amplication DTOs / utils, like BooleanFilter, SortOrder, will be placed in a new “util” module."
- [ ]  From the spec: "The users will be able to move the DTOs / Actions, that they created, between modules. This change will affect the generated code of all the users’ DTOs and Actions that are using this DTO.
- [ ]  From the spec: "The users will be able to duplicate a DTO / Action (the new DTO / Action will be called “Copy of”) - user DTO / Action or Amplication DTO / Action. The newly created DTO / Action will be located in the same module as the original DTO / Action."
- [ ]  Bug: Remove the "Delete" explanation next to the delete icon, and add it as a tooltip <img width="551" alt="image" src="https://github.com/amplication/amplication/assets/149934977/d505adef-8546-4897-8b17-fe9913255e54">
- [ ]  Bug: When deleting a “named” DTO - <img width="655" alt="image" src="https://github.com/amplication/amplication/assets/149934977/d3720fb2-20f9-4dd6-a66f-7d350fad36f1">
- [ ] https://github.com/amplication/amplication/issues/8229

**Comment by mulygottlieb** [comment]
Critical parts for the initial release as beta were handled. Moving the rest of this EPIC back to "todo" to prioritize the rest of it
@PazYanoverr
