### ISSUE TITLE
[Epic:`.NET`] DSG Catalog add support for  multi DSG images

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8369]
## Plugin api
- [x] Update plugin-api to allow generator-name dependency

## Plugin Catalog
- [x] add support for generators in plugins ( add specification for generator names )

## DSG Catalog
- [x] Add support for generator-name
- [ ] Update sync to retrieve generators (manual action)
- [x] Update sync to retrieve versions of active generators

**Comment by mulygottlieb** [comment]
Passed QA ✅
