### ISSUE TITLE
[Epic:`.NET`] Add support for generation of `Roles`

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8530]
Changes needed:
- [ ] update controller methods to have the correct `[Authorize(Roles="xxx,yyy,zzz")]` attributes. => will implemented in auth-plugin 
- [x] update `appsettings.json` generation to add the AmplicationRoles section: https://github.com/amplication/dotnet-8-api-sample/blob/main/src/appsettings.json#L12-L15 
- [ ] add static file https://github.com/amplication/dotnet-8-api-sample/blob/main/src/Infrastructure/RolesManager.cs to generation => will implemented in auth-plugin

**Comment by mulygottlieb** [comment]
Passed QA ✅
Tested in: https://github.com/muly-demo-repos/dotnet-tests-1
