### ISSUE TITLE
[Epic:`.NET`]  dotnet generation issues

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8539]
- [x] `ServiceCollectionExtensions` class must be `static`
- [x] Services interfaces `I****Service` are part of the wrong namespace (`<ResourceName>.APIs.Dtos` instead of `<ResourceName>.APIs`)
- [x] Services interfaces `I****Service` children related methods signature is wrong 
- [x] All methods of Services interfaces `I****Service` are wrongly formatted. interfaces don't store code blocks. 

       ```cs
       // WRONG
        public Task DeleteTodoItem(TodoItemIdDto idDto) { } 
       // CORRECT
         public Task DeleteTodoItem(TodoItemIdDto idDto);
        ```

- [x] Dtos are part of the wrong namespace ( `<EntityName>.APIs.Dtos` instead of `<ResourceName>.APIs.Dtos`)
- [x] Controllers are missing the required references (i.e. `Microsoft.AspNetCore.Mvc`)
- [x] ControllerBase classes are missing the reference for `NotFoundException` (it should be `<ResourceName>.APIs.Errors`)
- [x] Controller and ControllerBase are missing the `_service` protected property
- [x] Entity Extensions must be `static` but they are not 
- [x] Entity Extensions `ToDto` method is not correctly generated. Entity properties must be PascalCase
- [x] Models (in Infrastructure) have properties that don't follow the right naming convention. All properties are camelCase instead of PascalCase
- [x] All models data annotations (i.e. `[Key]` or `[Required]`) are missing reference to `System.ComponentModel.DataAnnotations`
- [x] `[Table("Author")]` attributes are missing the correct reference `System.ComponentModel.DataAnnotations.Schema`
- [x] Static files namespace should be updated to base namespace
- [x] ServiceBase is missing reference to `****.Infrastructure`
- [x] Infrastructure Models properties don't respect the input.json (optional props are generated as mandatory)
- [x] DbContext DI configuration was not matching the naming
- [x] Services createEntity methods don't match template
- [x] Services methods are not generated correctly
- [x] Services extensions are generated broken
- [x] Find children in one-to-many relation is broken
- [x] Infrastructure Models id property of one-2-many relations are generated with wrong type. i.e. WorkspaceId should be of the same type of the Workspace Id
- [x] MS SQL Server plugin generate program.cs with typo

**Comment by overbit** [comment]
- [x] `ServiceCollectionExtensions` class must be `static` [fix(generator-dotnet-webapi): service collection extension class to be static](https://github.com/amplication/generator-dotnet-webapi/commit/38e3161b5074182b465760ca34452cf79fd7d342)
- [ ] Services interfaces `I****Service` are part of the wrong namespace (`<ResourceName>.APIs.Dtos` instead of `<ResourceName>.APIs`)
- [ ] All methods of Services interfaces `I****Service` are wrongly formatted. interfaces don't store code blocks. 

       ```cs
       // WRONG
        public Task DeleteTodoItem(TodoItemIdDto idDto) { } 
       // CORRECT
         public Task DeleteTodoItem(TodoItemIdDto idDto);
        ```

- [ ] Dtos are part of the wrong namespace ( `<EntityName>.APIs.Dtos` instead of `<ResourceName>.APIs.Dtos`)
- [ ] Controllers are missing the required references (i.e. `Microsoft.AspNetCore.Mvc`)
- [ ] ControllerBase classes are missing the reference for `NotFoundException` (it should be `<ResourceName>.APIs.Errors`)
- [ ] Controller and ControllerBase are missing the `_service` protected property
- [x] Entity Extensions must be `static` but they are not [fix(generator-dotnet-webapi): api extension classes to be static](https://github.com/amplication/generator-dotnet-webapi/commit/cac70e9b759a15b451007e6322ca6dad6692c856)
- [ ] Entity Extensions `ToDto` method is not correctly generated. Entity properties must be PascalCase
- [ ] Models (in Infrastructure) have properties that don't follow the right naming convention. All properties are camelCase instead of PascalCase
- [ ] All models data annotations (i.e. `[Key]` or `[Required]`) are missing reference to `System.ComponentModel.DataAnnotations`
- [ ] `[Table("Author")]` attributes are missing the correct reference `System.ComponentModel.DataAnnotations.Schema`

**Comment by mulygottlieb** [comment]
Passed QA ✅
Tested in: https://github.com/muly-demo-repos/dotnet-tests-1
