### ISSUE TITLE
[Epic:`.NET`] Handle generation of enums

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8554]
- [x] Update the sample code for example of Enum definitions and using them as members of a DTO
- [ ] Update our dotnet-DSG code to generate custom enums
- [ ] Update our dotnet-DSG code to generate enums for "Option Set" fields in DB models

example: https://github.com/amplication/dotnet-8-api-sample/commit/42b8cfb36d19628aacf7c3fcf6ba94e37b75f681 

---

1. create enum files (Core/Enums)
2. connect the enum (to the model and the dto fields)
3. custom enum (create-enum + custom dto enum field type + enum as an input + enum as an output)
