### ISSUE TITLE
[Epic:`.NET`] Align all the build-in DTOs that appear in the UI under the entity-related-modules (e.g. CustomerFindManyArgs) VS the actual dotnet DTOs

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8556]
We need to decide which "way" to align - either change the dotnet generated code to use the same DTOs we use for Nest (that appear in the UI), or - change the auto-created-DTOs in the server according to the chosen tech-stack for the service (align the blocks and UI to the actual generated code).
This needs to be discussed internally first (Mango)

**Comment by overbit** [comment]
This needs to be reviewed as the current generation is not using the same DTOs @mulygottlieb @morhag90

**Comment by mulygottlieb** [comment]
Moving this back into "Todo" until we have the discussion which side to align to which side

**Comment by mulygottlieb** [comment]
Tech notes for implementation:
Server:
- [ ] Filter out GQL-only DTOs in the server in the ModuleDTO Resolver
- [ ] 
Dotnet DSG:
- [ ] Rename non-GQL DTOs to the names we have in the server
- [ ] Change the [Entity]IdDto - rename, do not inherit in the [Entity] DTO and instead add the id with its id-type directly

**Comment by morhag90** [comment]
Passed QA:

Forbbiden: 
<img width="1469" alt="image" src="https://github.com/amplication/amplication/assets/97830649/78d96590-c02e-4278-97af-681e3c4b17e7">

Authorize + FindOne => Not Found:
<img width="1466" alt="image" src="https://github.com/amplication/amplication/assets/97830649/04ed5aac-9983-4ad4-9d51-7af8fc9ba26d">

Create One entity:

<img width="1309" alt="image" src="https://github.com/amplication/amplication/assets/97830649/b2f6f85e-9299-4658-8670-3ffafb0d0c64">

FindMany:

<img width="1245" alt="image" src="https://github.com/amplication/amplication/assets/97830649/58a0570f-aeda-4fdc-a1d2-1fcb60af7d7a">

Get one entity:

<img width="1386" alt="image" src="https://github.com/amplication/amplication/assets/97830649/c682b379-4ed8-4ec3-bdf5-47bdf5c3ddf0">
 
Create one entity with another entity relation:

<img width="1468" alt="image" src="https://github.com/amplication/amplication/assets/97830649/7b1ec613-d39f-4456-a263-bda5a6eecc50">
 
The other side:

<img width="1078" alt="image" src="https://github.com/amplication/amplication/assets/97830649/7a1ceecc-603e-44a7-98d7-d21c2938e8ed">

**Comment by mulygottlieb** [comment]
Retuning to qa just to qa the dto filtering in the server as well.

**Comment by mulygottlieb** [comment]
Passed QA:

Generation part:

![Image](https://github.com/amplication/amplication/assets/1912933/95f985ae-214c-4257-afb9-5c6a4f4c1c0b)

![Image](https://github.com/amplication/amplication/assets/1912933/1841c918-d932-4850-b8ef-4bc70c6b8062)


DTO filter:

![Image](https://github.com/amplication/amplication/assets/1912933/c2719994-df7f-4c98-8db5-27443d0a0fe7)

![Image](https://github.com/amplication/amplication/assets/1912933/a857fe58-bf04-45a7-9ca7-05f1cffdfebe)
