### ISSUE TITLE
[Epic:`.NET`] Runtime issues

### ISSUE THREAD

**Issue by overbit** [amplication/amplication#8566]
- [x] FindMany endpoints return `System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name') en-us is an invalid culture identifier.`
- [ ] [[server] Failed to execute plugin event CreateServerDockerCompose. ENOENT: no such file or directory, open '/workspace/packages/generator-dotnet-webapi/src/server/docker-compose/Dockerfile' View details](https://app.amplication-sandbox.com/clvxww3gw00b96ir9b81tk63l/clvxww3uc00bc6ir9x7cqxeg1/commits/clwsyy0nf0000m2kig9khd05q)
- [ ] logs errors {"buildId":"clwt20flm00017lh2k38kxolg-server","cause":{"code":"ECONNRESET"},"code":"ECONNRESET","component":"generator-dotnet-webapi","config":{"adapter":

**Comment by mulygottlieb** [comment]
Passed QA ✅
Tested in: https://github.com/muly-demo-repos/dotnet-tests-1
