### ISSUE TITLE
[Epic:`.NET`] Test the generated code in multiple scenarios and fix as needed for a stable generated code

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8611]
Test Cases:
- [x] Basic service with CRUD
- [ ] Entity relations of all kinds (1:1, 1:n, n:n)
- [ ] Auth and roles
- [ ] Custom actions in entity modules
- [ ] Custom actions in custom modules
- [ ] Using custom DTOs and built-in DTOs in custom actions
- [ ] Using custom Enums in custom actions
- [ ] Verify both DB plugins on a basic scenario with some entities and relations
- [ ] Special field types - JSON, Option Set, Multi-select Option Set, etc. 

Issues found so far:
- Optional relations are not optional - you can't create a customer without an address, although address is optional
- Warnings on relations when running the migrations about splitting to two relations since ForeignKey was specified on both sides
- PG migration not working - connection string in docker-compose file seem wrong for Postgres and there is some additional issues after that to actually connect to the DB to run the migrations
- SQL server migrations failed when adding FKs - complaining about circular cascade path and recommending to use onDelete=NoAction instead of onDelete=Cascade

**Comment by mulygottlieb** [comment]
Passed QA ✅
Tested in: https://github.com/muly-demo-repos/dotnet-tests-1
