### ISSUE TITLE
Epic: Add Private Plugin functionality (leftovers)

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8863]
**P0:**

**P1 (Ordered):**
- [ ] Add a new private plugin by choosing between the available folders instead of typing the name of the plugin
      * The current practice is error-prone. 
- [ ] Validate and enforce relations between private plugins to plugin installation
      * What happens when deleting a private plugin which is installed in a service?
      * What happens when there is no plugin in the repo (anymore), but a private plugin is installed? For now- getting errors in the build time
      * Improve experience when disabling private plugin - As for now, the user can disable a private plugin (in the Plugin Repo resource). Then- the plugin is ignored in build time (for all relevant services), but still available for selection in the Plugins screen (-  while adding "(Disabled)" to the plugin name)
- [ ] Convert the plugin repo to be used as a tab in the project
      * Instead of a resource
      * For now, it is allowed to create multiple instances of Plugin Repos resource. However, in case of more than one such resource, build time error is issued
      * When adding a new Private Plugins tab- there should probably be only one repo for the plugins (at least in the first phase)
- [ ] Fetch isPrivate from the server and use it to show a special indication in the UI
- [ ] Add support to upload plugin ICON (or URL)

**P2:**
- [ ] Add support for defining a plugin folder on git in the plugin repo configuration (relative path)
- [ ]  Use isPrivate parameter when installing from another source
      * Currently it is based on the category; "tech" only issue, not functional
- [ ] Implement cache to skip private plugin downloads when not needed
      * For now, the code is downloaded every build
