### ISSUE TITLE
EPIC: React Admin support for .NET and other React Admin improvements

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#8874]
- [ ] Upgrade the GQL react admin to latest RA (version 5)
- [ ] Allow the Node DSG to generate the react admin either with GQL or REST provider by a parameter from the DSG Resource Data
- [ ] Enhance the "split build" logic of the Build Manager to allow running different DSG versions/images for the server VS for the admin
- [ ] Add UI options to let the user choose to generate Admin UI in .NET projects
- [ ] Use the "split build" logic to run a .NET DSG for the server + Node DSG for the REST-React-Admin
- [ ] Allow Node services to create admin UI with REST
- [ ] Consider separating the Admin to a new DSG with its own version management (expose version choice to the user)

**Comment by mulygottlieb** [comment]
@PazYanoverr to prioritize

**Comment by PazYanoverr** [comment]
Placed it in the Todo tasks based on the ticket's priority. Thanks

**Comment by mulygottlieb** [comment]
@PazYanoverr I returned this to the Todo status and extracted the first sub-ticket for immediate work (https://github.com/amplication/amplication/issues/8891).
After the first subticket is done, we will re-evaluate if/when we should progress on the next subtasks of this epic.

**Comment by PazYanoverr** [comment]
@mulygottlieb - Sounds good, thanks!
I would suggest extracting all the tickets of the first phase, prioritizing them, and moving the Epic (with the next-phase tasks) to the backlog.
WDYT?

**Comment by mulygottlieb** [comment]
Agreed @PazYanoverr .
For now only the first task (upgrade to react-admin 5) was already decided as s first phase, and this was extracted to a ticket. I will now backlog this epic and we can return to other parts of it whenever we want.

**Comment by PazYanoverr** [comment]
Thanks @mulygottlieb.
I will move the ticket to "Next" so we can remember to discuss it in the coming weeks
