### ISSUE TITLE
Epic: Versions of Service Template  & Private Plugins

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9002]
General:
- [ ] Build the infrastructure for an indication / notification system

Private Plugins:
- [ ] PP: New option- “In development”
- [ ] PP: Support only enable/disable for a specific version

Service Catalog:
- [ ] Service Catalog: Add an indication for the "Code Gen Version" which is not the latest
- [ ] Service Catalog: Add an indication for plugins whose last successful build != the latest version

Service Template
- [ ] Templates Overview: Display the template version of each template
- [ ] Templates Overview: Display the installed plugins of each template
- [ ] Templates Overview: Add an indication for plugins whose chosen version != the latest version
- [ ] Template Versions: The versions display should include the changes in each version
- [ ] Template Versions: The versions display should include services using each version

Plugins Screen
- [ ] Plugins Screen: Display the relevant versions of each plugin
- [ ] Plugins Screen: PP's list of versions should include the user's comments
- [ ] Plugins Screen: Add a filter for the plugins which need "attention"
