### ISSUE TITLE
Epic: Catalog Improvements

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#9290]
Based on https://www.notion.so/amplication/Service-Catalog-Definitions-13beb180667180b9a760ec1e7d4e7965?pvs=4

Urgent:
- [x] #9291
- [x] #9297

P0:
- [ ] #9292
- [ ] #9293
- [ ] #9295
- [ ] #9296

P1:
- [ ] Update the Project Catalog component to be the same as the Workspace Catalog
- [ ] Workspace and Project Catalog: add an indication next to the Template name for the project/workspace type of the Template
- [ ] Add pagination option to the Catalog
- [ ] Save the filter definitions in the local storage (per user, per catalog- workspace / project)
- [x] #9294
