### ISSUE TITLE
Epic: Roles

### ISSUE THREAD

**Issue by yuval-hazaz** [amplication/amplication#9481]
- [X] https://github.com/amplication/amplication/issues/9478
- [X] https://github.com/amplication/amplication/issues/9479
- [ ] Assign roles to teams
- [ ] Create a decorator to validate specific permissions 
- [ ] Validate access on the server based on role permissions
- [ ] Validate access on the client based on role permissions
- [ ]

**Comment by pancham-singh** [comment]
@yuval-hazaz  can you assign this one.
